###
GET http://localhost:8080/ElegantAccelerationService-1.0-SNAPSHOT/api/acceleration/requests/count
#

###
POST http://localhost:8080/ElegantAccelerationService-1.0-SNAPSHOT/api/acceleration/requests
Accept: application/json
Content-Type: application/json

{
  "functionCode": "foo0",
  "deviceInfo": {
    "deviceName" : "Nvidia GPU",
    "doubleFPSupport" : true,

    "deviceAddressBits" : 64,
    "deviceType" : "CL_DEVICE_TYPE_GPU",
    "deviceExtensions" : "cl_khr_int64_base_atomics",
    "availableProcessors" : 12
  }
}

###
POST http://localhost:8080/ElegantAccelerationService-1.0-SNAPSHOT/api/acceleration/requests
Accept: application/json
Content-Type: application/json

{
  "functionCode": "foo1",
  "deviceInfo": {
    "deviceName" : "Nvidia GPU 1",
    "doubleFPSupport" : true,
    "maxWorkItems": {
      "dim1" : 12,
      "dim2" : 1,
      "dim3" : 1
    },
    "deviceAddressBits" : 64,
    "deviceType" : "CL_DEVICE_TYPE_GPU",
    "deviceExtensions" : "cl_khr_int64_base_atomics",
    "availableProcessors" : 12
  }
}

###
POST http://localhost:8080/ElegantAccelerationService-1.0-SNAPSHOT/api/acceleration/requests
Accept: application/json
Content-Type: application/json

{
  "functionCode": "foo2",
  "deviceInfo": {
    "deviceName" : "Nvidia GPU 2",
    "doubleFPSupport" : false,
    "maxWorkItems": {
      "dim1" : 16,
      "dim2" : 1,
      "dim3" : 1
    },
    "deviceAddressBits" : 12,
    "deviceType" : "CL_DEVICE_TYPE_GPU",
    "deviceExtensions" : "cl_khr_int64_base_atomics",
    "availableProcessors" : 128
  }
}

###
POST http://localhost:8080/ElegantAccelerationService-1.0-SNAPSHOT/api/acceleration/requests
Accept: application/json
Content-Type: application/json

{
  "functionCode": "foo3",
  "deviceInfo": {
    "deviceName" : "Nvidia GPU 3",
    "doubleFPSupport" : true,
    "maxWorkItems": {
      "dim1" : 1,
      "dim2" : 1,
      "dim3" : 1
    },
    "deviceAddressBits" : 32,
    "deviceType" : "CL_DEVICE_TYPE_GPU",
    "deviceExtensions" : "cl_khr_int64_base_atomics",
    "availableProcessors" : 1024
  }
}

###
GET http://localhost:8080/ElegantAccelerationService-1.0-SNAPSHOT/api/acceleration/requests
#

###
PUT http://localhost:8080/ElegantAccelerationService-1.0-SNAPSHOT/api/acceleration/requests/2
Accept: application/json
Content-Type: application/json

{
  "functionCode": "foo2",
  "deviceInfo": {
    "deviceName" : "Nvidia GPU 10",
    "doubleFPSupport" : true,
    "maxWorkItems": {
      "dim1" : 1024,
      "dim2" : 64,
      "dim3" : 1
    },
    "deviceAddressBits" : 64,
    "deviceType" : "CL_DEVICE_TYPE_GPU",
    "deviceExtensions" : "cl_khr_int64_base_atomics",
    "availableProcessors" : 65536
  }
}

###
DELETE http://localhost:8080/ElegantAccelerationService-1.0-SNAPSHOT/api/acceleration/requests/2

###
GET http://localhost:8080/ElegantAccelerationService-1.0-SNAPSHOT/api/acceleration/requests
#

###
GET http://localhost:8080/ElegantAccelerationService-1.0-SNAPSHOT/api/acceleration/requests/2
#
