###
POST http://localhost:8080/ElegantAccelerationService-1.0-SNAPSHOT/api/acceleration/requests/submit
Accept: multipart/form-data
Content-Type: multipart/form-data; boundary=abcd

--abcd
Content-Disposition: form-data; name="vectorAdd"; filename="vectorAdd.java"

< ./inputFiles/vectorAdd.java
--abcd
Content-Disposition: form-data; name="deviceInfo"; filename="deviceInfo.json"

< ./inputFiles/deviceInfo.json

###
GET http://localhost:8080/ElegantAccelerationService-1.0-SNAPSHOT/api/acceleration/requests/count
#

###
GET http://localhost:8080/ElegantAccelerationService-1.0-SNAPSHOT/api/acceleration/requests/1
#

###
POST http://localhost:8080/ElegantAccelerationService-1.0-SNAPSHOT/api/acceleration/requests/1/resubmit
Accept: multipart/form-data
Content-Type: multipart/form-data; boundary=abcd

--abcd
Content-Disposition: form-data; name="vectorAdd"; filename="vectorAdd.cpp"

< ./inputFiles/vectorAdd.cpp
--abcd
Content-Disposition: form-data; name="deviceInfo"; filename="deviceInfo2.json"

< ./inputFiles/deviceInfo2.json

###
GET http://localhost:8080/ElegantAccelerationService-1.0-SNAPSHOT/api/acceleration/requests/1
#

###
POST http://localhost:8080/ElegantAccelerationService-1.0-SNAPSHOT/api/acceleration/requests/submit
Accept: multipart/form-data
Content-Type: multipart/form-data; boundary=abcd

--abcd
Content-Disposition: form-data; name="vectorAdd"; filename="vectorAdd.java"

< ./inputFiles/vectorAdd.java
--abcd
Content-Disposition: form-data; name="deviceInfo"; filename="deviceInfo.json"

< ./inputFiles/deviceInfo.json

###
GET http://localhost:8080/ElegantAccelerationService-1.0-SNAPSHOT/api/acceleration/requests
#

###
GET http://localhost:8080/ElegantAccelerationService-1.0-SNAPSHOT/api/acceleration/requests/2
#

###
DELETE http://localhost:8080/ElegantAccelerationService-1.0-SNAPSHOT/api/acceleration/requests/2

###
GET http://localhost:8080/ElegantAccelerationService-1.0-SNAPSHOT/api/acceleration/requests/1
#

###
GET http://localhost:8080/ElegantAccelerationService-1.0-SNAPSHOT/api/acceleration/requests/1/state
#

###
POST http://localhost:8080/ElegantAccelerationService-1.0-SNAPSHOT/api/acceleration/requests/1/resubmit
Accept: multipart/form-data
Content-Type: multipart/form-data; boundary=abcd

--abcd
Content-Disposition: form-data; name="vectorAdd"; filename="vectorAdd.java"

< ./inputFiles/vectorAdd.java
--abcd
Content-Disposition: form-data; name="deviceInfo"; filename="deviceInfo.json"

< ./inputFiles/deviceInfo.json

###
DELETE http://localhost:8080/ElegantAccelerationService-1.0-SNAPSHOT/api/acceleration/requests/1
#

###
GET http://localhost:8080/ElegantAccelerationService-1.0-SNAPSHOT/api/acceleration/requests/count
#
