###
GET http://localhost:8080/ElegantAccelerationService-1.0-SNAPSHOT/api/acceleration/count
#

###

# curl -X POST -H "Content-Type: multipart/form-data" -F "codeFile=@examples/inputFiles/vectorAdd.java" -F "jsonFile=@examples/inputFiles/deviceInfoJava.json" http://localhost:8080/ElegantAccelerationService-1.0-SNAPSHOT/api/acceleration/submit
POST http://localhost:8080/ElegantAccelerationService-1.0-SNAPSHOT/api/acceleration/submit
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="codeFile"; filename="vectorAdd.java"

< ./inputFiles/vectorAdd.java
--WebAppBoundary
Content-Disposition: form-data; name="jsonFile"; filename="deviceInfoJava.json"

< ./inputFiles/deviceInfoJava.json
--WebAppBoundary--

###

###
GET http://localhost:8080/ElegantAccelerationService-1.0-SNAPSHOT/api/acceleration/1/retrieve
#

###
GET http://localhost:8080/ElegantAccelerationService-1.0-SNAPSHOT/api/acceleration/1/state
#

###

# curl -X POST -H "Content-Type: multipart/form-data" -F "codeFile=@examples/inputFiles/vectorAdd2.java" -F "jsonFile=@examples/inputFiles/deviceInfoJava2.json" http://localhost:8080/ElegantAccelerationService-1.0-SNAPSHOT/api/acceleration/1/resubmit
POST http://localhost:8080/ElegantAccelerationService-1.0-SNAPSHOT/api/acceleration/1/resubmit
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="codeFile"; filename="vectorAdd2.java"

< ./inputFiles/vectorAdd2.java
--WebAppBoundary
Content-Disposition: form-data; name="jsonFile"; filename="deviceInfoJava2.json"

< ./inputFiles/deviceInfoJava2.json
--WebAppBoundary--

###

###
DELETE http://localhost:8080/ElegantAccelerationService-1.0-SNAPSHOT/api/acceleration/1
#

